### ISSUE TITLE
Uploading file extra arguments

### ISSUE THREAD

**Issue by gridcell** [dlite-tools/aws-s3-tools#28]
## Summary

Add optional function argument to set boto's `ExtraArgs` when uploading files.

## Basic usage examples

**upload_file_to_key:**

```python
upload_file_to_key(
    "myBucket",
    "cat.jpg",
    "/Users/bill/Pictures/cat.jpg",
    extra_args={
        "Tagging": "owner=bill",
        "Content-Type": "image/jpeg"
    }
)
```

**upload_files_to_keys:**
```python
upload_files_to_keys(
    bucket="myBucket",
    paths_keys=[
        ("/Users/bill/Pictures/cat.jpg", "cat.jpg", {"Tagging": "owner=bill", "Content-Type": "image/jpeg"}),
        ("/Users/bill/Pictures/cat.png", "dog.png", {"Tagging": "owner=bill", "Content-Type": "image/png"}),
    ]
)
```

## Motivation

**Use Case:** When using an S3 bucket as a static website and uploading the images to bucket the content type isn't being set.  When accessing images in a browser, a file download is triggered instead of displaying images.

**Comment by tomassosorio** [comment]
Hey @gridcell , sorry for the delay, I will do the PR in the following days to include this feature.

**Comment by FerrariDG** [comment]
PR with functionality #29
